apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secrets
  namespace: easyshop
type: Opaque
stringData:
  JWT_SECRET: "4684406321a80a1bcebe92c6feb9fb14bbdf21136190f0864a0dad693f6c3044"
  NEXTAUTH_SECRET: "NGHsdCPD/3uDmun6+KTJ3tV21Z62RkJxKRr72WvxNes="
